// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-Pphj3LeH-LoIkuJCSBdiD408ZIL5x04',
    appId: '1:840119001871:web:33469b8590ec4317c1547a',
    messagingSenderId: '840119001871',
    projectId: 'ecofin-1744b',
    authDomain: 'ecofin-1744b.firebaseapp.com',
    storageBucket: 'ecofin-1744b.firebasestorage.app',
    measurementId: 'G-5CJQGRLW9Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQoUqQZTVJv1XiBL5aCjcBG-C2fY-IkgA',
    appId: '1:840119001871:android:e649f1764dc84185c1547a',
    messagingSenderId: '840119001871',
    projectId: 'ecofin-1744b',
    storageBucket: 'ecofin-1744b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxZ6WaKucZ51C1SXHvpfSZYCnFihbCMrs',
    appId: '1:840119001871:ios:79a0afdce4f694c9c1547a',
    messagingSenderId: '840119001871',
    projectId: 'ecofin-1744b',
    storageBucket: 'ecofin-1744b.firebasestorage.app',
    iosBundleId: 'com.example.ecofin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxZ6WaKucZ51C1SXHvpfSZYCnFihbCMrs',
    appId: '1:840119001871:ios:79a0afdce4f694c9c1547a',
    messagingSenderId: '840119001871',
    projectId: 'ecofin-1744b',
    storageBucket: 'ecofin-1744b.firebasestorage.app',
    iosBundleId: 'com.example.ecofin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-Pphj3LeH-LoIkuJCSBdiD408ZIL5x04',
    appId: '1:840119001871:web:c3d4b319dc05e6f1c1547a',
    messagingSenderId: '840119001871',
    projectId: 'ecofin-1744b',
    authDomain: 'ecofin-1744b.firebaseapp.com',
    storageBucket: 'ecofin-1744b.firebasestorage.app',
    measurementId: 'G-WPBFYZVL1M',
  );
}
